### PR TITLE
expose JavaScript API

### PR DESCRIPTION
**Pull request by cancerberoSgx**
This is my current work (WIP) regarding https://github.com/Tw1ddle/geometrize-haxe-web/issues/3. I just want to share it with you for review and discuss. WIP!

 * exposes classes Bitmap, ShapeJsonExporter, SvgExporter, ImageRunnerOptions, ImageRunner, ShapeType as you suggested
 * adds build-js-target.hxml (please review)
 * adds a simple browser example and build instructions. https://cancerberosgx.github.io/demos/geometrize-js-api-example/
 * adds simple node.js Command line tool example and build instructions
 * added method Bitmap.createFromRawBytes (since JavaScript users cannot access Bytes haxe standard library class which seems to be needed for building a Bitmap)

**IMPORTANT**: In order to not pollute this library with JavaScript stuff, maybe is better that this PR only contains changes related to exposing haxe classes and nothing else. Then, we can create an independent project geometrize-js which contains the library, examples and documentation. What do you think ? 

TODO 

- [ ] reference shapes using ShapeTypes in example
- [ ] documentation
- [ ] render PNG example

Nice to have (but perhaps in another project?)

- [ ]  TypeScript type definitions
- [ ] package.json and npm publish
- [ ] tests

### CODE REVIEW

**Comment by Tw1ddle** [comment]
Very good! I've committed the @:exposes and ShapeType constants: https://github.com/Tw1ddle/geometrize-haxe/commit/305b9348b76fadd43a8d27b1ded9677ae249f68d

Perhaps you could create a separate repository that contains a submodule, like my web demo repo?

TypeScript definitions, this .d.ts generator might work though it's a WIP: https://github.com/nadako/hxtsdgen - the creator is really skilled and wants feedback.

**Comment by Tw1ddle** [comment]
Added function ```createFromByteArray``` to Bitmap.hx: https://github.com/Tw1ddle/geometrize-haxe/commit/b4b89247d44d82a3b233ff5dd46b758d8952034f

For the .hxml, I think you could include the lib in one line like this: https://github.com/Tw1ddle/geometrize-haxe-web/blob/master/GeometrizeHaxeWeb.hxml#L7

**Comment by cancerberoSgx** [comment]
I think those changes are all I need :) I'm now creating the following node.js projects (tell me if that's fine):

 * geometrize-js : 
   - zero-dependencies
   - contains a copy of geometrize.js file (output of haze compile), build-js.hxml, TypeScript typings api docs and build instructions. 
   - contains tests that verify it exports classes/objects the typings declare
   - contains tests that verify happy path for exporters in node.js and in the browser (using puppeteer)
   - No implementation on my side, users will be calling the generated lib directly.
 * geometrize-js-cli: uses geometrize-js to provide a command line interface
 * geometrize-js-playground (private) a web demo using geometrize-js similar to geometrize-haxe-web testing the library in a real world app

I already have implemented geometrize-jswith tests and the playground as react application and is looking fine !!! :) In the typings I took the liberty of copy&paste your haxedocs.

I will update the status here right?

Please let me know if you agree or have any concerns. 

Thanks! (it was really easy to do this, haxe was very friendly) :)

**Comment by Tw1ddle** [comment]
Sounds like a good plan to me. Let me know if I can help at all. I'll link your work in the readme etc when you're ready :smile:

One request, if you make a commercial app please don't use "geometrize" or "primitive" as the name for it, to avoid confusion. Also, include the MIT license text: https://raw.githubusercontent.com/Tw1ddle/geometrize-haxe/master/LICENSE and, optionally, mention primitive and geometrize in the credits.

**Pull request closed without merging**
